<?php
/*  
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; under version 2
 * of the License (non-upgradable).
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * 
 * Copyright (c) 2007-2010 (original work) Public Research Centre Henri Tudor & University of Luxembourg) (under the project TAO-QUAL);
 *               2008-2010 (update and modification) Deutsche Institut für Internationale Pädagogische Forschung (under the project TAO-TRANSFER);
 *               2009-2012 (update and modification) Public Research Centre Henri Tudor (under the project TAO-SUSTAIN & TAO-DEV);
 * 
 */
?>
<?php
/**
 * @author CRP Henri Tudor - TAO Team - {@link http://www.tao.lu}
 * @license GPLv2  http://www.opensource.org/licenses/gpl-2.0.php
 * @package wfEngine
 */
require_once dirname(__FILE__).'/../includes/raw_start.php';
require_once dirname(__FILE__).'/SaSManager.php';

/**
 * Enable you to export all the sas.xml contents to the wiki format 
 * (usefull to create the documentation of the services)
 * 
 * @author Bertrand Chevrier <bertrand.chevrier@tudor.lu>
 *
 */
class SaSWiki extends SasManager{
	
	/**
	 * @var string path to xsl sheet
	 */
	protected $xslFile =  'wikize.xsl';
	
	/**
	 * @var string path to the output file
	 */
	protected $outputFile = 'output.txt';
	
 	/**
 	 * Constructor
 	 * Initialize the files
 	 */
	public function __construct(){
		
		parent::__construct();

		if(!file_exists($this->xslFile)){
			throw new Exception("Unable to found the xsl file {$this->xslFile}");
		}
		
		file_put_contents($this->outputFile, '');
	}
	
	/**
	 * Main entry point
	 * Perform the XSLT transformation on the found sas.xml files to transform the xml content to the wiki format
	 * Create an output.xml file containing the export 
	 * @return boolean
	 */
	public function transform(){
		
		$this->log('Sas 2 Wiki', true);
		
		$sasFiles = $this->getSasFiles();
		
		$doc = new DOMDocument();
		$doc->load($this->xslFile);
		$xsl = new XSLTProcessor();
		$xsl->importStyleSheet($doc);

		$buffer = '';
		foreach($sasFiles as $sasFile){
			$this->log('perform transformation on '.$sasFile);
			$doc->load($sasFile);
			$buffer .= $xsl->transformToXML($doc);
		}
		if(!empty($buffer)){
			$content = "====== List of services ======
The sections below give us the list of all available services in the process authoring tool. 
So you can use each of these TAO's chunk to build your services.";   
			$content .= "\n$buffer\n";
			$content .= "''Generated by wfEngine/scripts/wikiSas.php : SaSWiki::transform on ".date('Y-m-d')."''";
			
		}
		if(file_put_contents($this->outputFile, $content)){
			$this->log($this->outputFile." created");
			return true;
		}
		return false;
	}	
}

/*
 * Run the exporter by calling me
 */
$mySaSWiki = new SaSWiki();
$mySaSWiki->transform();

?>